### ISSUE TITLE
a.m. Feedback to wider group

### ISSUE THREAD

**Issue by Sarina00** [CodeTheCity/aliss#9]
Hi Douglas,

feel free to ask the 3 of us for any details you need to enhance this - :-)

**Comment by Dougie37** [comment]
hi James 

Looking for a short update from you?

**Comment by Sarina00** [comment]
especially due to being 3 people down at present - we have listed all the tasks as issues so that we do not lose track of them.  We can also see what needs doing next.  Once done I will assist Beth or anyone else where I can :-)  

I hope that is ok.

**Comment by Dougie37** [comment]
that's fine,

**Comment by Sarina00** [comment]
completed
